/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './app/**/*.{js,jsx}',
    './src/**/*.{js,jsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },

        normal: {
          catTypeInner: '#837d6d',
          catTypeBorder: '#5d5747',
          baseStatsSecondInner: '#f4eede',
          baseStatsSecondBorder: '#e1dbcb',
          baseStatsMainInner: '#ece6d6',
          baseStatsMainBorder: '#dad4c4',
          rightBodyInner: '#f4eede',
          rightBorderTopBottom: '#cec9a9',
          rightBorderOutDark: '#bfb9a9',
          rightBorderOutLight: '#e1dbcb',
          abilityInner: '#9d9787',
          abiliyBorder: '#767060',
          hiddenAbilityInner: '#b0aa9a',
          hiddenAbilityBorder: '#807a6a',
          heightInner: '#bcb6a6',
          heightBorder: '#bbb5a5',
          weightInner: '#cfc9b9',
          weightBorder: '#a19b8b',
          genderInner: '#dbd5c5',
          genderBorder: '#bbb5a5',
          eggInner: '#ebe5d5',
          eggBorder: '#ebe5d5'
        },
        electric: {
          catTypeInner: '#a78d17',
          catTypeBorder: '#7c6917',
          baseStatsSecondInner: '#fff0b1',
          baseStatsSecondBorder: '#ffe35d',
          baseStatsMainInner: '#ffeb8e',
          baseStatsMainBorder: '#fbdd4b',
          rightBodyInner: '#fff0b1',
          rightBorderTopBottom: '#f1d341',
          rightBorderOutDark: '#e3c533',
          rightBorderOutLight: '#ffe35d',
          abilityInner: '#c4a717',
          abiliyBorder: '#998217',
          hiddenAbilityInner: '#d6b826',
          hiddenAbilityBorder: '#a38b17',
          heightInner: '#e0c230',
          heightBorder: '#bb9e17',
          weightInner: '#f2d342',
          weightBorder: '#c8aa18',
          genderInner: '#fcde4c',
          genderBorder: '#e0c130',
          eggInner: '#ffea89',
          eggBorder: '#eacc3a'
        },
        bug: {
          catTypeInner: '#818c24',
          catTypeBorder: '#5b6601',
          baseStatsSecondInner: '#f1f9ae',
          baseStatsSecondBorder: '#dee69b',
          baseStatsMainInner: '#e9f1a6',
          baseStatsMainBorder: '#d7df94',
          rightBodyInner: '#f1f9ae',
          rightBorderTopBottom: '#ccd76f',
          rightBorderOutDark: '#bdc860',
          rightBorderOutLight: '#dee69b',
          abilityInner: '#9ba63e',
          abiliyBorder: '#747f17',
          hiddenAbilityInner: '#aeb951',
          hiddenAbilityBorder: '#7e8921',
          heightInner: '#bac55d',
          heightBorder: '#939e36',
          weightInner: '#cad877',
          weightBorder: '#9faa42',
          genderInner: '#d6e38b',
          genderBorder: '#b9c266',
          eggInner: '#e8f0a5',
          eggBorder: '#c4cc81'
        },
        dark: {
          catTypeInner: '#6c4f53',
          catTypeBorder: '#4b3539',
          baseStatsSecondInner: '#f3e8eb',
          baseStatsSecondBorder: '#ded3d6',
          baseStatsMainInner: '#eadfe2',
          baseStatsMainBorder: '#d6cbce',
          rightBodyInner: '#f3e8eb',
          rightBorderTopBottom: '#d7c1c8',
          rightBorderOutDark: '#ded3d6',
          rightBorderOutLight: '#c8b2b9',
          abilityInner: '#92757d',
          abiliyBorder: '#664e54',
          hiddenAbilityInner: '#a98c95',
          hiddenAbilityBorder: '#70575b',
          heightInner: '#b89ba4',
          heightBorder: '#896b73',
          weightInner: '#d0b3bb',
          weightBorder: '#977a82',
          genderInner: '#dec2ca',
          genderBorder: '#b79aa2',
          eggInner: '#ecd9de',
          eggBorder: '#c0acb2'
        },
        dragon: {
          catTypeInner: '#6763d3',
          catTypeBorder: '#433fa9',
          baseStatsSecondInner: '#ebebfb',
          baseStatsSecondBorder: '#d3d1f7',
          baseStatsMainInner: '#e0dff9',
          baseStatsMainBorder: '#cac8f5',
          rightBodyInner: '#ebebfb',
          rightBorderTopBottom: '#bbb9f2',
          rightBorderOutDark: '#d3d1f7',
          rightBorderOutLight: '#a9a6ef',
          abilityInner: '#837ee8',
          abiliyBorder: '#7a75e6',
          hiddenAbilityInner: '#9995ec',
          hiddenAbilityBorder: '#6460d0',
          heightInner: '#a7a3ef',
          heightBorder: '#7a75e6',
          weightInner: '#bcbaf3',
          weightBorder: '#8883e9',
          genderInner: '#cbc9f5',
          genderBorder: '#a6a2ee',
          eggInner: '#dfddf9',
          eggBorder: '#b4b0f1'
        },
        fairy: {
          catTypeInner: '#e287e0',
          catTypeBorder: '#d060ce',
          baseStatsSecondInner: '#fff0fe',
          baseStatsSecondBorder: '#fee1fd',
          baseStatsMainInner: '#feeafd',
          baseStatsMainBorder: '#fedcfc',
          rightBodyInner: '#fff0fe',
          rightBorderTopBottom: '#fed1fc',
          rightBorderOutDark: '#fee1fd',
          rightBorderOutLight: '#fdc5fb',
          abilityInner: '#f1a4ef',
          abiliyBorder: '#dd7bda',
          hiddenAbilityInner: '#fab7f7',
          hiddenAbilityBorder: '#e184df',
          heightInner: '#fdc5fb',
          heightBorder: '#ec9bea',
          weightInner: '#fed3fc',
          weightBorder: '#f2a3ef',
          genderInner: '#fedcfc',
          genderBorder: '#fdc1fb',
          eggInner: '#fee9fd',
          eggBorder: '#fdccfc'
        },
        fighting: {
          catTypeInner: '#b1574f',
          catTypeBorder: '#88342c',
          baseStatsSecondInner: '#fde4e2',
          baseStatsSecondBorder: '#fbc6c1',
          baseStatsMainInner: '#fcd8d4',
          baseStatsMainBorder: '#fabcb6',
          rightBodyInner: '#fde4e2',
          rightBorderTopBottom: '#f9aaa2',
          rightBorderOutDark: '#fbc6c1',
          rightBorderOutLight: '#f6938a',
          abilityInner: '#ce7067',
          abiliyBorder: '#a24b42',
          hiddenAbilityInner: '#e4837a',
          hiddenAbilityBorder: '#d2746b',
          heightInner: '#f29086',
          heightBorder: '#c56860',
          weightInner: '#f9aba3',
          weightBorder: '#d2746b',
          genderInner: '#fabdb8',
          genderBorder: '#f18f85',
          eggInner: '#fcd5d3',
          eggBorder: '#f8a097'
        },
        fire: {
          catTypeInner: '#cb6624',
          catTypeBorder: '#a34201',
          baseStatsSecondInner: '#ffeadc',
          baseStatsSecondBorder: '#ffd1b3',
          baseStatsMainInner: '#ffe0ca',
          baseStatsMainBorder: '#ffc8a4',
          rightBodyInner: '#ffeadc',
          rightBorderTopBottom: '#ffb98a',
          rightBorderOutDark: '#ffd1b3',
          rightBorderOutLight: '#ffa56a',
          abilityInner: '#e5803e',
          abiliyBorder: '#be5917',
          hiddenAbilityInner: '#f89351',
          hiddenAbilityBorder: '#c86321',
          heightInner: '#ffa164',
          heightBorder: '#dd7836',
          weightInner: '#ffba8c',
          weightBorder: '#e98442',
          genderInner: '#ffcaa6',
          genderBorder: '#ffa062',
          eggInner: '#ffdec8',
          eggBorder: '#ffb07b'
        },
        flying: {
          catTypeInner: '#5b7fcf',
          catTypeBorder: '#3559a9',
          baseStatsSecondInner: '#e8eeff',
          baseStatsSecondBorder: '#cddcff',
          baseStatsMainInner: '#dde7ff',
          baseStatsMainBorder: '#c3d5ff',
          rightBodyInner: '#e8eeff',
          rightBorderTopBottom: '#b2c9ff',
          rightBorderOutDark: '#9dbbff',
          rightBorderOutLight: '#cddcff',
          abilityInner: '#7599e9',
          abiliyBorder: '#4e72c2',
          hiddenAbilityInner: '#88acfc',
          hiddenAbilityBorder: '#587ccc',
          heightInner: '#99b8ff',
          heightBorder: '#6d91e1',
          weightInner: '#b4caff',
          weightBorder: '#799ded',
          genderInner: '#c5d6ff',
          genderBorder: '#97b7ff',
          eggInner: '#dbe6ff',
          eggBorder: '#a8c3ff'
        },
        ghost: {
          catTypeInner: '#8171b5',
          catTypeBorder: '#5b4b8f',
          baseStatsSecondInner: '#efebff',
          baseStatsSecondBorder: '#ded4ff',
          baseStatsMainInner: '#e8e2ff',
          baseStatsMainBorder: '#d7ccff',
          rightBodyInner: '#efebff',
          rightBorderTopBottom: '#ccbdff',
          rightBorderOutDark: '#bdadf1',
          rightBorderOutLight: '#ded4ff',
          abilityInner: '#9b8bcf',
          abiliyBorder: '#7464a8',
          hiddenAbilityInner: '#ae9ee2',
          hiddenAbilityBorder: '#7e6eb2',
          heightInner: '#baaaee',
          heightBorder: '#9383c7',
          weightInner: '#cdbeff',
          weightBorder: '#9f8fd3',
          genderInner: '#d8cdff',
          genderBorder: '#b9a9ed',
          eggInner: '#e7e0ff',
          eggBorder: '#c5b5f9'
        },
        grass: {
          catTypeInner: '#529e44',
          catTypeBorder: '#2c781e',
          baseStatsSecondInner: '#defdd1',
          baseStatsSecondBorder: '#bcf4aa',
          baseStatsMainInner: '#cffabf',
          baseStatsMainBorder: '#b5eda3',
          rightBodyInner: '#defdd1',
          rightBorderTopBottom: '#9de98f',
          rightBorderOutDark: '#8eda80',
          rightBorderOutLight: '#bcf4aa',
          abilityInner: '#6cb85e',
          abiliyBorder: '#459137',
          hiddenAbilityInner: '#7fcb71',
          hiddenAbilityBorder: '#4f9b41',
          heightInner: '#8bd77d',
          heightBorder: '#64b056',
          weightInner: '#a7e58f',
          weightBorder: '#70bc62',
          genderInner: '#b3f19b',
          genderBorder: '#8ad67c',
          eggInner: '#cdfabd',
          eggBorder: '#96e288'
        },
        ground: {
          catTypeInner: '#927d41',
          catTypeBorder: '#6c571b',
          baseStatsSecondInner: '#f7eed4',
          baseStatsSecondBorder: '#eadbae',
          baseStatsMainInner: '#f1e6c4',
          baseStatsMainBorder: '#e3d4a7',
          rightBodyInner: '#f7eed4',
          rightBorderTopBottom: '#d7c89b',
          rightBorderOutDark: '#c8b98c',
          rightBorderOutLight: '#e6dbb9',
          abilityInner: '#ac975b',
          abilityBorder: '#857034',
          hiddenAbilityInner: '#bfaa6e',
          hiddenAbilityBorder: '#8f7a3e',
          heightInner: '#cbb67a',
          heightBorder: '#a48f53',
          weightInner: '#dec98d',
          weightBorder: '#b09b5f',
          genderInner: '#ead599',
          genderBorder: '#cab579',
          eggInner: '#f0e5c3',
          eggBorder: '#d0c194',
        },
        ice: {
          catTypeInner: '#40959f',
          catTypeBorder: '#176d77',
          baseStatsSecondInner: '#d4f9fd',
          baseStatsSecondBorder: '#adedf5',
          baseStatsMainInner: '#c3f5fa',
          baseStatsMainBorder: '#a6e6ee',
          rightBodyInner: '#d4f9fd',
          rightBorderTopBottom: '#8be0ea',
          rightBorderOutDark: '#7cd1db',
          rightBorderOutLight: '#adedf5',
          abilityInner: '#5aafb9',
          abilityBorder: '#338892',
          hiddenAbilityInner: '#6dc2cc',
          hiddenAbilityBorder: '#3d929c',
          heightInner: '#79ced8',
          heightBorder: '#52a7b1',
          weightInner: '#8ce1eb',
          weightBorder: '#5eb3bd',
          genderInner: '#98edf7',
          genderBorder: '#78cdd7',
          eggInner: '#c0f4fa',
          eggBorder: '#84d9e3',
        },
        poison: {
          catTypeInner: '#7f4691',
          catTypeBorder: '#522b5f',
          baseStatsSecondInner: '#f4defa',
          baseStatsSecondBorder: '#e7b9f5',
          baseStatsMainInner: '#eecef8',
          baseStatsMainBorder: '#e3acf3',
          rightBodyInner: '#f4defa',
          rightBorderTopBottom: '#e8b0f6',
          rightBorderOutDark: '#d9a1e7',
          rightBorderOutLight: '#e7b9f5',
          abilityInner: '#a158b3',
          abilityBorder: '#6e3d80',
          hiddenAbilityInner: '#b970cc',
          hiddenAbilityBorder: '#7b448d',
          heightInner: '#c980db',
          heightBorder: '#9652a8',
          weightInner: '#d69ae7',
          weightBorder: '#995cab',
          genderInner: '#e3adf3',
          genderBorder: '#bb7fcd',
          eggInner: '#edccf8',
          eggBorder: '#cc8edd',
        },
        psychic: {
          catTypeInner: '#d94f78',
          catTypeBorder: '#b32952',
          baseStatsSecondInner: '#ffe6ee',
          baseStatsSecondBorder: '#ffcada',
          baseStatsMainInner: '#ffdae6',
          baseStatsMainBorder: '#ffbfd3',
          rightBodyInner: '#ffe6ee',
          rightBorderTopBottom: '#ffadc6',
          rightBorderOutDark: '#ff97b6',
          rightBorderOutLight: '#ffcada',
          abilityInner: '#f36992',
          abilityBorder: '#cc426b',
          hiddenAbilityInner: '#ff80a6',
          hiddenAbilityBorder: '#d64c75',
          heightInner: '#ff92b3',
          heightBorder: '#eb618a',
          weightInner: '#ffafc7',
          weightBorder: '#f76d96',
          genderInner: '#ffc1d4',
          genderBorder: '#ff91b2',
          eggInner: '#ffd9e5',
          eggBorder: '#ffa3bf',
        },
        rock: {
          catTypeInner: '#866a4d',
          catTypeBorder: '#61462c',
          baseStatsSecondInner: '#f5e9db',
          baseStatsSecondBorder: '#e6d1b9',
          baseStatsMainInner: '#f1dfca',
          baseStatsMainBorder: '#dec9b1',
          rightBodyInner: '#f5e9db',
          rightBorderTopBottom: '#d0bca4',
          rightBorderOutDark: '#bfab94',
          rightBorderOutLight: '#e6d1b9',
          abilityInner: '#a28466',
          abilityBorder: '#795e41',
          hiddenAbilityInner: '#b69879',
          hiddenAbilityBorder: '#a6896a',
          heightInner: '#c4a586',
          heightBorder: '#997c5f',
          weightInner: '#d9bb9a',
          weightBorder: '#a6896a',
          genderInner: '#e7c8a6',
          genderBorder: '#c3a485',
          eggInner: '#f0dec8',
          eggBorder: '#c8b39c',
        },
        steel: {
          catTypeInner: '#7c7a8f',
          catTypeBorder: '#565469',
          baseStatsSecondInner: '#eeecff',
          baseStatsSecondBorder: '#dad8ed',
          baseStatsMainInner: '#e5e3f8',
          baseStatsMainBorder: '#d3d1e6',
          rightBodyInner: '#eeecff',
          rightBorderTopBottom: '#c7c5da',
          rightBorderOutDark: '#b8b6cb',
          rightBorderOutLight: '#dad8ed',
          abilityInner: '#9694a9',
          abilityBorder: '#6f6d82',
          hiddenAbilityInner: '#a9a7bc',
          hiddenAbilityBorder: '#79778c',
          heightInner: '#b5b3c8',
          heightBorder: '#8e8ca1',
          weightInner: '#c8c6db',
          weightBorder: '#9a98ad',
          genderInner: '#d4d2e7',
          genderBorder: '#b4b2c7',
          eggInner: '#e4e2f7',
          eggBorder: '#c0bed3',
        },
        water: {
          catTypeInner: '#3d8ecc',
          catTypeBorder: '#1768a6',
          baseStatsSecondInner: '#e1f2ff',
          baseStatsSecondBorder: '#bfe3ff',
          baseStatsMainInner: '#d3ebff',
          baseStatsMainBorder: '#b2ddff',
          rightBodyInner: '#e1f2ff',
          rightBorderTopBottom: '#9cd4ff',
          rightBorderOutDark: '#81c8ff',
          rightBorderOutLight: '#bfe3ff',
          abilityInner: '#57a8e6',
          abilityBorder: '#3081bf',
          hiddenAbilityInner: '#6abbf9',
          hiddenAbilityBorder: '#3a8bc9',
          heightInner: '#7cc6ff',
          heightBorder: '#4fa0de',
          weightInner: '#9ed5ff',
          weightBorder: '#5bacea',
          genderInner: '#b4deff',
          genderBorder: '#7ac5ff',
          eggInner: '#d1ebff',
          eggBorder: '#90ceff',
        },

      },

      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },

      keyframes: {
        "gradient": {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' }
        },
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },

      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "gradient": "gradient 2s ease infinite"
      },

      fontFamily: {
        rubikburned: ['"Rubik Burned"'],
      }
    },
  },
  plugins: [require("tailwindcss-animate")],
}